---
strict: true
site_name: stories-django
site_description: Stories library integration with Django framework.
theme:
  name: material
  palette:
    scheme: default
    primary: deep-purple
    accent: deep-purple
  icon:
    logo: material/language-python
    repo: fontawesome/brands/github
  language: en
  features:
    - navigation.instant
    - navigation.tabs
repo_name: proofit404/stories-django
repo_url: https://github.com/proofit404/stories-django
edit_uri: ""
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.magiclink
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
extra_javascript:
  - javascripts/extra.js
nav:
  - Home:
      - Home: index.md
      - Installation: installation.md
      - Changelog: changelog.md
  - Usage:
      - Debug Toolbar: debug_toolbar.md
